name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  install_dev:
    required: false
    default: '1'
  level:
    required: false
    default: '0'
  run_tests: 
    required: false
    default: ''
  dirs: 
    required: false
    default: ''
  config_file:
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.install_dev }}
    - ${{ inputs.level }}
    - ${{ inputs.run_tests }}
    - ${{ inputs.dirs }}
    - ${{ inputs.config_file }}
