name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        env:
          INSTALL_DEV: '0'
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
